### ISSUE TITLE
how does this work

### ISSUE THREAD

**Issue by osnapitzjamie** [sychen52/nest-camera-site#1]
how does this work?

I get this error:
https://i.imgur.com/BGtsTeO.png

**Comment by sychen52** [comment]
Have you done "npm install" first?

**Comment by jaanraadik** [comment]
I followed the instructions in Readme.md, then after getting this same error found this same issue. Anything else you'd reccomend?

**Comment by sychen52** [comment]
I have added the instruction for openssl to generate keys for https.
