### ISSUE TITLE
docker image?

### ISSUE THREAD

**Issue by jmvaz** [sychen52/nest-camera-site#4]
Hi!

There is some docker image with this app?

Thanks,

**Comment by sychen52** [comment]
So far no.

**Comment by nextshell** [comment]
I'm willing to make one provided I can actually make it work! I can't progress pass authentication and I also don't see any new files/folders been created for recording.

**Comment by nextshell** [comment]
PR here: https://github.com/sychen52/nest-camera-site/pull/6

**Comment by sychen52** [comment]
Finished in https://github.com/sychen52/nest-camera-site/pull/6
