### ISSUE TITLE
Am I supposed to be able to login to https://ip:5000?

### ISSUE THREAD

**Issue by kkuhle** [sychen52/nest-camera-site#5]
Are we supposed to be able to see our cam images here?  A folder called "nest" gets created and the images are stored there, but I can't log into the web interface even after deleting database.json and resetting up new credentials.

**Comment by sychen52** [comment]
https://ip:5000

**Comment by kkuhle** [comment]
Yes, I see the login page on https://ip:5000 and am prompted for a username/password, but it doesn't do anything after I enter them.  It redirects me back to the login page.  I've tested on Chrome and Firefox.

**Comment by sychen52** [comment]
Have you setup your username and password on the command line?

**Comment by kkuhle** [comment]
Yes.  If I remove database.json, it prompts me to create new credentials when I start the app, but they won't log me in when I go to the server in a browser.  The images are still there when is nice, but being able to access the site might be better.

Any way to create a log for the problem logging in?

**Comment by sychen52** [comment]
I did not log that part. If you are willing to try, you can add log around line 32 and 33 in index.js file.

**Comment by nextshell** [comment]
I'm having the same issue, I've never been able to login!

**Comment by nextshell** [comment]
I wonder if this is the issue! 
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.

**Comment by sychen52** [comment]
Hi guys, I just added a few lines of log in the user login part. I need to know where you guys failed. Could you git pull and try login again, and paste the console log here?

**Comment by nextshell** [comment]
Hi, thanks for your reply! 
```
npm run start 
> nest-camera-site@1.0.0 start /home/atar/playground/nest-camera-site
> node index

Server started on port 5000
login user:  atar
verify password
null
login user:  atar
verify password
```
Where it says `null` I've tried a wrong password!

**Comment by sychen52** [comment]
Thank you for testing it out. I just committed another patch. It may have already fixed it. If not, could you please try again and paste the console log here?

**Comment by nextshell** [comment]
(master)*$ npm run start 

> nest-camera-site@1.0.0 start /home/atar/playground/nest-camera-site
> node index

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::5000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Object.<anonymous> (/home/atar/playground/nest-camera-site/index.js:85:37)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

npm ERR! Linux 5.3.0-42-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! nest-camera-site@1.0.0 start: `node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nest-camera-site@1.0.0 start script 'node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nest-camera-site package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nest-camera-site
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nest-camera-site
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/atar/playground/nest-camera-site/npm-debug.log

**Comment by nextshell** [comment]
npm run start

> nest-camera-site@1.0.0 start /home/atar/playground/nest-camera-site
> node index

Server started on port 5000
verify password. hash type: string ; hash length: 60
passed

**Comment by nextshell** [comment]
it didn't work yet

**Comment by sychen52** [comment]
It says passed. So the password verification part is working. Then it is a
browser redirection issue. Which browser are you using? Could you try
Firefox or chrome. And your OS that runs the npm?

**Comment by nextshell** [comment]
Same issue with 3 different browsers, chrome, firefox, brave!
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

I don't have another OS!

**Comment by sychen52** [comment]
This time, I think I fixed it. Please let me know whether it works. Thanks again for testing this.

**Comment by nextshell** [comment]
Yep, that worked!

**Comment by sychen52** [comment]
Fixed in https://github.com/sychen52/nest-camera-site/commit/3c94539b92add31cd68562b4f620138835400681
