### ISSUE TITLE
database.json missing when building docker image

### ISSUE THREAD

**Issue by drash1** [sychen52/nest-camera-site#9]
Hello,
I'm trying to build the docker image but it failed because of a missing database.json:

`Step 6/11 : COPY database.json database.json
COPY failed: stat /var/lib/docker/tmp/docker-builder576663390/database.json: no such file or directory`

I can't find any information about that file, am I missing something?

**Comment by sychen52** [comment]
Just fixed in f20c283a6d8bb802c8b1172276f5ae04830d191a. Could you please try it out?

**Comment by drash1** [comment]
Yes, works now Thanks!
